import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  QUOTE_DOCUMENT_CONTENT_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_FILE_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_STATUS_ACCEPTED,
  QUOTE_DOCUMENT_STATUS_DRAFT,
  QUOTE_DOCUMENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_STATUS_GENERATED,
  QUOTE_DOCUMENT_STATUS_OPTION_ACCEPTED_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_STATUS_OPTION_GENERATED_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_STATUS_OPTION_REJECTED_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_STATUS_OPTION_SENT_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_STATUS_REJECTED,
  QUOTE_DOCUMENT_STATUS_SENT,
  QUOTE_DOCUMENT_TOTAL_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: QUOTE_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'quoteDocument',
  namePlural: 'quoteDocuments',
  labelSingular: 'Quote/Invoice',
  labelPlural: 'Quotes & Invoices',
  description: 'A generated quote or invoice produced from a template and a customer record.',
  icon: 'IconFile',
  labelIdentifierFieldMetadataUniversalIdentifier:
    QUOTE_DOCUMENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: QUOTE_DOCUMENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Document name, e.g. "Quote — ACME Corp".',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: QUOTE_DOCUMENT_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Where this document is in its lifecycle.',
      icon: 'IconProgress',
      defaultValue: `'${QUOTE_DOCUMENT_STATUS_DRAFT}'`,
      options: [
        {
          id: QUOTE_DOCUMENT_STATUS_OPTION_DRAFT_UNIVERSAL_IDENTIFIER,
          value: QUOTE_DOCUMENT_STATUS_DRAFT,
          label: 'Draft',
          color: 'gray',
          position: 0,
        },
        {
          id: QUOTE_DOCUMENT_STATUS_OPTION_GENERATED_UNIVERSAL_IDENTIFIER,
          value: QUOTE_DOCUMENT_STATUS_GENERATED,
          label: 'Generated',
          color: 'green',
          position: 1,
        },
        {
          id: QUOTE_DOCUMENT_STATUS_OPTION_SENT_UNIVERSAL_IDENTIFIER,
          value: QUOTE_DOCUMENT_STATUS_SENT,
          label: 'Sent',
          color: 'blue',
          position: 2,
        },
        {
          id: QUOTE_DOCUMENT_STATUS_OPTION_ACCEPTED_UNIVERSAL_IDENTIFIER,
          value: QUOTE_DOCUMENT_STATUS_ACCEPTED,
          label: 'Accepted',
          color: 'turquoise',
          position: 3,
        },
        {
          id: QUOTE_DOCUMENT_STATUS_OPTION_REJECTED_UNIVERSAL_IDENTIFIER,
          value: QUOTE_DOCUMENT_STATUS_REJECTED,
          label: 'Rejected',
          color: 'red',
          position: 4,
        },
      ],
    },
    {
      universalIdentifier: QUOTE_DOCUMENT_CONTENT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'content',
      label: 'Content',
      description: 'The rendered document text, with all placeholders filled.',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: QUOTE_DOCUMENT_TOTAL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'totalAmount',
      label: 'Total amount',
      description: 'Sum of all line-item amounts on this document.',
      icon: 'IconCurrency',
    },
    {
      universalIdentifier: QUOTE_DOCUMENT_FILE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.FILES,
      name: 'file',
      label: 'File',
      description: 'The generated document as a downloadable PDF.',
      icon: 'IconFileTypePdf',
      universalSettings: { maxNumberOfValues: 1 },
    },
  ],
});
