import { defineObject, FieldType, NumberDataType, STANDARD_OBJECTS as STANDARD_OBJECT } from 'twenty-sdk/define';

import {
  SKU_BASEPRICE_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_CODE_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_COMPANYREVERSE_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_COMPANYSEGMENT_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_COMPANY_SEGMENT_ENTERPRISE,
  SKU_COMPANY_SEGMENT_OPTION_ENTERPRISE_UNIVERSAL_IDENTIFIER,
  SKU_COMPANY_SEGMENT_OPTION_RETAIL_UNIVERSAL_IDENTIFIER,
  SKU_COMPANY_SEGMENT_OPTION_SME_UNIVERSAL_IDENTIFIER,
  SKU_COMPANY_SEGMENT_RETAIL,
  SKU_COMPANY_SEGMENT_SME,
  SKU_CURRENCY_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_DECOMMISSIONED_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_LLMPERMINUTECOST_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_NOTE_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_OBJECT_UNIVERSAL_IDENTIFIER,
  SKU_ONETIMESETUPFEE_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_PROVIDERNAME_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_SELLINGPRICE_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_SETUPFEEDIFFICULTY_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_SETUPFEEMAX_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_SETUPFEEMIN_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_SETUP_FEE_DIFFICULTY_HIGH,
  SKU_SETUP_FEE_DIFFICULTY_LOW,
  SKU_SETUP_FEE_DIFFICULTY_MEDIUM,
  SKU_SETUP_FEE_DIFFICULTY_OPTION_HIGH_UNIVERSAL_IDENTIFIER,
  SKU_SETUP_FEE_DIFFICULTY_OPTION_LOW_UNIVERSAL_IDENTIFIER,
  SKU_SETUP_FEE_DIFFICULTY_OPTION_MEDIUM_UNIVERSAL_IDENTIFIER,
  SKU_SIPMONTHLYRENTAL_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_SIPPERMINUTECOST_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_UNIT_PRICE_FIELD_UNIVERSAL_IDENTIFIER,
  SKU_VERSION_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: SKU_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'sku',
  namePlural: 'skus',
  labelSingular: 'SKU',
  labelPlural: 'SKUs',
  description: 'Your price catalog — every sellable product or service with its pricing and provider details.',
  icon: 'IconBarcode',
  labelIdentifierFieldMetadataUniversalIdentifier: SKU_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: SKU_CODE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'code',
      label: 'SKU code',
      description: 'Unique stock-keeping unit, e.g. "SV-1001".',
      icon: 'IconBarcode',
    },
    {
      universalIdentifier: SKU_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Product or service name.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: SKU_DESCRIPTION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'description',
      label: 'Description',
      description: 'What the customer gets.',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: SKU_VERSION_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'version',
      label: 'Version',
      description: 'Version of this SKU, e.g. "v1" or "v2".',
      icon: 'IconVersions',
    },
    {
      universalIdentifier: SKU_DECOMMISSIONED_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.BOOLEAN,
      name: 'decommissioned',
      label: 'Decommissioned',
      description: 'Whether this SKU is retired and no longer sold.',
      icon: 'IconCircleOff',
    },
    {
      universalIdentifier: SKU_BASEPRICE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'basePrice',
      label: 'Base price',
      description: 'The base/floor price before mark-up.',
      icon: 'IconCurrency',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_SELLINGPRICE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'sellingPrice',
      label: 'Selling price',
      description: 'The price we actually sell at.',
      icon: 'IconCurrencyDollar',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_UNIT_PRICE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'unitPrice',
      label: 'Unit price',
      description: 'Price for one unit (kept for compatibility with quotes/invoices).',
      icon: 'IconCurrency',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_CURRENCY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'defaultCurrency',
      label: 'Currency',
      description: 'Currency code, e.g. MYR.',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: SKU_PROVIDERNAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'providerName',
      label: 'Provider name',
      description: 'The vendor or service provider this SKU is sourced from.',
      icon: 'IconBuildingSkyscraper',
    },
    {
      universalIdentifier: SKU_COMPANYSEGMENT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'companySegment',
      label: 'Company segment',
      description: 'Which market segment this SKU is priced for.',
      icon: 'IconChartPie',
      defaultValue: `'${SKU_COMPANY_SEGMENT_SME}'`,
      options: [
        { id: SKU_COMPANY_SEGMENT_OPTION_ENTERPRISE_UNIVERSAL_IDENTIFIER, value: SKU_COMPANY_SEGMENT_ENTERPRISE, label: 'Enterprise', color: 'blue', position: 0 },
        { id: SKU_COMPANY_SEGMENT_OPTION_SME_UNIVERSAL_IDENTIFIER, value: SKU_COMPANY_SEGMENT_SME, label: 'SME', color: 'turquoise', position: 1 },
        { id: SKU_COMPANY_SEGMENT_OPTION_RETAIL_UNIVERSAL_IDENTIFIER, value: SKU_COMPANY_SEGMENT_RETAIL, label: 'Retail individual', color: 'green', position: 2 },
      ],
    },
    {
      universalIdentifier: SKU_SIPPERMINUTECOST_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'sipPerMinuteCost',
      label: 'SIP per minute cost',
      description: 'Cost per minute for SIP minutes (e.g. RM0.18).',
      icon: 'IconPhone',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_SIPMONTHLYRENTAL_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'sipMonthlyRental',
      label: 'SIP monthly rental',
      description: 'Monthly rental for the SIP number (e.g. RM18).',
      icon: 'IconPhone',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_LLMPERMINUTECOST_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'llmPerMinuteCost',
      label: 'LLM per minute cost',
      description: 'Cost per minute of AI/LLM usage (e.g. RM0.15).',
      icon: 'IconBrain',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_ONETIMESETUPFEE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'oneTimeSetupFee',
      label: 'One-time setup fee',
      description: 'Base one-time setup fee (e.g. RM350).',
      icon: 'IconSettings',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_SETUPFEEMIN_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'setupFeeMin',
      label: 'Setup fee (min)',
      description: 'Lower bound of the setup fee range.',
      icon: 'IconCurrency',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_SETUPFEEMAX_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'setupFeeMax',
      label: 'Setup fee (max)',
      description: 'Upper bound of the setup fee range.',
      icon: 'IconCurrency',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: SKU_SETUPFEEDIFFICULTY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'setupFeeDifficulty',
      label: 'Setup difficulty',
      description: 'How complex the setup is, which drives where in the fee range it falls.',
      icon: 'IconGauge',
      defaultValue: `'${SKU_SETUP_FEE_DIFFICULTY_MEDIUM}'`,
      options: [
        { id: SKU_SETUP_FEE_DIFFICULTY_OPTION_LOW_UNIVERSAL_IDENTIFIER, value: SKU_SETUP_FEE_DIFFICULTY_LOW, label: 'Low', color: 'green', position: 0 },
        { id: SKU_SETUP_FEE_DIFFICULTY_OPTION_MEDIUM_UNIVERSAL_IDENTIFIER, value: SKU_SETUP_FEE_DIFFICULTY_MEDIUM, label: 'Medium', color: 'orange', position: 1 },
        { id: SKU_SETUP_FEE_DIFFICULTY_OPTION_HIGH_UNIVERSAL_IDENTIFIER, value: SKU_SETUP_FEE_DIFFICULTY_HIGH, label: 'High', color: 'red', position: 2 },
      ],
    },
    {
      universalIdentifier: SKU_NOTE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'note',
      label: 'Note',
      description: 'Any additional notes about this SKU.',
      icon: 'IconNotes',
    },
  ],
});

