import { defineObject, FieldType, NumberDataType } from 'twenty-sdk/define';

import {
  VOIP_PROVIDER_ADDRESS_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_DATE_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_INVOICENUMBER_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_OBJECT_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_OUTCOME_APPROVED,
  VOIP_PROVIDER_OUTCOME_COMPLETED,
  VOIP_PROVIDER_OUTCOME_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_OUTCOME_OPTION_APPROVED_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_OUTCOME_OPTION_COMPLETED_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_OUTCOME_OPTION_PENDING_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_OUTCOME_OPTION_REJECTED_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_OUTCOME_PENDING,
  VOIP_PROVIDER_OUTCOME_REJECTED,
  VOIP_PROVIDER_REMARKS_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_SUPPLIER_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_TIER_1,
  VOIP_PROVIDER_TIER_2,
  VOIP_PROVIDER_TIER_3,
  VOIP_PROVIDER_TIER_4,
  VOIP_PROVIDER_TIER_FIELD_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_TIER_OPTION_TIER_1_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_TIER_OPTION_TIER_2_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_TIER_OPTION_TIER_3_UNIVERSAL_IDENTIFIER,
  VOIP_PROVIDER_TIER_OPTION_TIER_4_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: VOIP_PROVIDER_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'voipProvider',
  namePlural: 'voipProviders',
  labelSingular: 'VoIP provider purchase',
  labelPlural: 'VoIP provider purchases',
  description: 'A record of a purchase made from a voip provider purchase.',
  icon: 'IconPhone',
  labelIdentifierFieldMetadataUniversalIdentifier: VOIP_PROVIDER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: VOIP_PROVIDER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      description: 'Short reference for this purchase.',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: VOIP_PROVIDER_DATE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.DATE,
      name: 'date',
      label: 'Date',
      description: 'Date of the purchase.',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: VOIP_PROVIDER_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.NUMBER,
      name: 'amount',
      label: 'Amount',
      description: 'Purchase amount.',
      icon: 'IconCurrency',
      universalSettings: { dataType: NumberDataType.FLOAT, decimals: 2 },
    },
    {
      universalIdentifier: VOIP_PROVIDER_INVOICENUMBER_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'invoiceNumber',
      label: 'Invoice number',
      description: 'Invoice or order number from the supplier.',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: VOIP_PROVIDER_SUPPLIER_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'supplier',
      label: 'Supplier',
      description: 'Supplier name (free text). Link to a company or person using the relations if available.',
      icon: 'IconBuildingSkyscraper',
    },
    {
      universalIdentifier: VOIP_PROVIDER_ADDRESS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'purchaseAddress',
      label: 'Address',
      description: 'Supplier or delivery address.',
      icon: 'IconMap',
    },
    {
      universalIdentifier: VOIP_PROVIDER_REMARKS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'remarks',
      label: 'Remarks',
      description: 'Notes about this purchase.',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: VOIP_PROVIDER_OUTCOME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'outcome',
      label: 'Outcome',
      description: 'Current outcome of this purchase.',
      icon: 'IconProgress',
      defaultValue: `'${VOIP_PROVIDER_OUTCOME_PENDING}'`,
      options: [
        { id: VOIP_PROVIDER_OUTCOME_OPTION_PENDING_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_OUTCOME_PENDING, label: 'Pending', color: 'gray', position: 0 },
        { id: VOIP_PROVIDER_OUTCOME_OPTION_APPROVED_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_OUTCOME_APPROVED, label: 'Approved', color: 'blue', position: 1 },
        { id: VOIP_PROVIDER_OUTCOME_OPTION_COMPLETED_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_OUTCOME_COMPLETED, label: 'Completed', color: 'green', position: 2 },
        { id: VOIP_PROVIDER_OUTCOME_OPTION_REJECTED_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_OUTCOME_REJECTED, label: 'Rejected', color: 'red', position: 3 },
      ],
    },
    {
      universalIdentifier: VOIP_PROVIDER_TIER_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'tier',
      label: 'Tier',
      description: 'Service or pricing tier of this purchase.',
      icon: 'IconLayers',
      defaultValue: `'${VOIP_PROVIDER_TIER_1}'`,
      options: [
        { id: VOIP_PROVIDER_TIER_OPTION_TIER_1_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_TIER_1, label: 'Tier 1', color: 'blue', position: 0 },
        { id: VOIP_PROVIDER_TIER_OPTION_TIER_2_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_TIER_2, label: 'Tier 2', color: 'turquoise', position: 1 },
        { id: VOIP_PROVIDER_TIER_OPTION_TIER_3_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_TIER_3, label: 'Tier 3', color: 'green', position: 2 },
        { id: VOIP_PROVIDER_TIER_OPTION_TIER_4_UNIVERSAL_IDENTIFIER, value: VOIP_PROVIDER_TIER_4, label: 'Tier 4', color: 'orange', position: 3 },
      ],
    },
  ],
});

